NAME: "BaiduAPI"
VERSION: "v0.0.1"
TOKEN_URL: "http://aip.baidubce.com/oauth/2.0/token"
TTS_SHORT_URL: "http://tsn.baidu.com/text2audio"
TTS_LONG_CREATE_URL: "https://aip.baidubce.com/rpc/2.0/tts/v1/create"
TTS_LONG_QUERY_URL: "https://aip.baidubce.com/rpc/2.0/tts/v1/query"
LENGTH_THRESHOLD: 500
PER: 0
SPD: 5
PIT: 5
VOL: 5
AUE: 6
LAN: "zh"
AK: "xxx"
SK: "xxx"