NAME: "OpenaiAgent"
VERSION: "v0.0.1"
# 暴露给前端的参数选项以及默认值
PARAMETERS: [
  {
    NAME: "OPENAI_BASE_URL",
    DEFAULT: "https://api.openai.com/v1"
  },
  {
    NAME: "OPENAI_API_MODEL",
    DEFAULT: "gpt-3.5-turbo"
  },
  {
    NAME: "OPENAI_API_KEY",
    DEFAULT: ""
  }
]