NAME: "GoogleAPI"
VERSION: "v0.0.1"
KEY: ""
# https://stackoverflow.com/questions/14257598/what-are-language-codes-in-chromes-implementation-of-the-html5-speech-recogniti/14302134#14302134
LANGUAGE: "zh-CN"